### PR TITLE
spec: add port ranges

### LINKED ISSUE #272: spec: need a way to declare a range of ports
Some apps utilize a range of public ports (e.g. FTP server) and appc should support this use case. Any router will have an option to DMZ a range of ports as a demonstration that it's a valid use case.

### PR DESCRIPTION
**Pull request by eyakubovich**
Fixes #272

### CODE REVIEW

**Comment by jonboulle** [comment]
general comments:
1) could you please add a bit more detail to the commit message for posterity (e.g. the top comment from #272)
2) tests

**Comment by eyakubovich** [comment]
@jonboulle I actually wrote the tests but didn't add them to the commit.

**Comment by jonboulle** [comment]
@eyakubovich just try not to add any binaries this time ;-)

On Mon, Apr 27, 2015 at 4:10 PM, Eugene Yakubovich <notifications@github.com

**Comment by jonboulle** [comment]
LGTM

**Pull request merged**
