### PR TITLE
*: appc v0.8.4

### PR DESCRIPTION
**Pull request by jonboulle**

### CODE REVIEW

**Comment by elemoine** [comment]
This PR broke the installation of appc/spec for me:

```
$ go get github.com/appc/spec/schema
# github.com/appc/spec/schema/types
/home/elemoine/.gvm/pkgsets/go1.6/snap/src/github.com/appc/spec/schema/types/isolator_resources.go:158: cannot use req (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.6/snap/src/github.com/appc/spec/schema/types/isolator_resources.go:159: cannot use lim (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.6/snap/src/github.com/appc/spec/schema/types/isolator_resources.go:212: cannot use req (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.6/snap/src/github.com/appc/spec/schema/types/isolator_resources.go:213: cannot use lim (type resource.Quantity) as type *resource.Quantity in field value
```

**Comment by steveeJ** [comment]
> This PR broke the installation of appc/spec for me:

This shouldn't happen. Please provide your `go version` information

**Comment by elemoine** [comment]
```
$ go version
go version go1.6 linux/amd64
```

**Comment by jonboulle** [comment]
It's because of a mismatch in versions between dependencies.
We will move appc/spec to using the vendor/ experiment which should fix
this.

**Comment by elemoine** [comment]
FYI, I am seeing the same issue with go 1.5:

```
$ gvm install go1.5
Installing go1.5...
 * Compiling...
go1.5 successfully installed!
$ gvm use go1.5
Now using version go1.5
$ gvm pkgset create test
$ gvm pkgset use test
Now using version go1.5@test
$ go get github.com/appc/spec/schema
# github.com/appc/spec/schema/types
/home/elemoine/.gvm/pkgsets/go1.5/test/src/github.com/appc/spec/schema/types/isolator_resources.go:158: cannot use req (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.5/test/src/github.com/appc/spec/schema/types/isolator_resources.go:159: cannot use lim (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.5/test/src/github.com/appc/spec/schema/types/isolator_resources.go:212: cannot use req (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.5/test/src/github.com/appc/spec/schema/types/isolator_resources.go:213: cannot use lim (type resource.Quantity) as type *resource.Quantity in field value
```

**Comment by jonboulle** [comment]
@elemoine The problem is that k8s introduced a breaking change in https://github.com/kubernetes/kubernetes/commit/b2a01d4d94090b5efd81d0b71cb21bbb932c053a and your go get is retrieving that version of the package. We do vendor in the repository but go get doesn't understand that because we haven't moved to the vendor experiment (yet). If you check out the repository and build using ./build it should work fine.

**Comment by elemoine** [comment]
I am quite new to Go but it seems to me that all packages that depend on `appc/spec/schema` are broken by this.

I initially found the problem while installing Snap (https://github.com/intelsdi-x/snap/issues/953). But here's another example:

```
$ go get k8s.io/kubernetes/pkg/kubelet
# github.com/appc/spec/schema/types
/home/elemoine/.gvm/pkgsets/go1.5/test/src/github.com/appc/spec/schema/types/isolator_resources.go:158: cannot use req (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.5/test/src/github.com/appc/spec/schema/types/isolator_resources.go:159: cannot use lim (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.5/test/src/github.com/appc/spec/schema/types/isolator_resources.go:212: cannot use req (type resource.Quantity) as type *resource.Quantity in field value
/home/elemoine/.gvm/pkgsets/go1.5/test/src/github.com/appc/spec/schema/types/isolator_resources.go:213: cannot use lim (type resource.Quantity) as type *resource.Quantity in field value
```

Sounds like a big issue to me. Not something I should work-around by checking out the repository and do ``./build``. No?

**Comment by jonboulle** [comment]
@elemoine can you try this again now?

**Comment by elemoine** [comment]
It works. Thanks a lot!

**Pull request merged**
