### PR TITLE
travis: enable go 1.5

### PR DESCRIPTION
**Pull request by marineam**

### CODE REVIEW

**Comment by vbatts** [comment]
does this imply go1.5 latest? (go1.5.1?)

**Comment by jonboulle** [comment]
@vbatts doesn't look like it:
https://travis-ci.org/appc/spec/jobs/80700384#L96

**Comment by marineam** [comment]
Updated to include minor go versions. I think it used to mean latest but travis has since changed the tool they use to manage go.

**Comment by jonboulle** [comment]
Thanks.

**Pull request merged**
