### PR TITLE
schema: add arm linux as valid arch

### PR DESCRIPTION
**Pull request by philips**
appc/spec#284 as per comment by philips in coreos/rkt#730.

### CODE REVIEW

**Comment by philips** [comment]
Deprecates #285

**Comment by jonboulle** [comment]
historical discussion here: https://github.com/appc/spec/issues/6#issuecomment-66525116

**Comment by philips** [comment]
We are going to wait on this one until we can get more guidance on what types of ARM strings we should have here. It gets a little tricky because the ARM architecture has a number of types such as "armel", "armhf" and whatever arm64. We want to make sure we have a list and docs that understand these differences. If anyone knows of an authoritative list please let us know.

**Comment by erikano** [comment]
@philips That is true. In the original issues I opened (appc/spec#284 and coreos/rkt#730), you may note that I was talking about "armhf" and "armv7l". The former ("armhf") is the label Ubuntu and Debian at least are using in their packaging systems. The latter ("armv7l") is what is reported by `uname -m` on the same system -- this ties into the issue raised by @mpasternacki and linked to by @jonboulle above in that it is probably too specific a name to be useful.

Would you be willing to add just "armhf" initially? Or would that be a misnomer in the context of Go, you think?

I might also add that on my ARM computer, I have run the "armhf" Debian in a chroot on "armhf" Ubuntu, so at least to me, "armhf" seems to be a useful label to adopt.

Likewise, on an old Android phone I used to have, "armel" Debian was able to run in a chroot.

Furthermore, as `sudo docker search armhf-` will show you, at least some people are using the label "armhf" for their docker images and while this is not docker, it may be of use to note that.

**Comment by philips** [comment]
@erikano Yea, I want to be able to document our decision. I don't know where the canonical source is for these strings.

**Comment by cnelson** [comment]
Looks like they are just made up by the devs working on the port

https://wiki.debian.org/ArmHardFloatPort

See notes on arrmel vs arm and naming debate 

-- 
cnelson

**Comment by philips** [comment]
We are trying to get a more authoritative answer offline with some folks involved in these projects, stay tuned.

**Comment by jonboulle** [comment]
@philips I think we established that for now we can at least add aarch64,
right? That one seems to be clearly defined and standardised (even if not
yet widely implemented)

**Comment by philips** [comment]
On Thu, Apr 9, 2015 at 6:34 PM, Jonathan Boulle <notifications@github.com>
wrote:

> @philips I think we established that for now we can at least add aarch64,
> right?
>

Yes, we can add aarch64. Maybe even aarch32?!

**Comment by jonboulle** [comment]
deprecated (again) by #304

**Pull request closed without merging**
