### PR TITLE
spec: allow empty App.Exec in image manifest.

### PR DESCRIPTION
**Pull request by yifan-gu**
As ACE can override and replace the App.Exec section, we should allow
empty App.Exec. This also allows some docker images that have empty
CMD/Entrypoint to be transformed to ACIs.

### CODE REVIEW

**Comment by vcaputo** [comment]
Seems reasonable to me, why not allow acis without an exec in the spec?

lgtm

**Comment by jonboulle** [comment]
fixes #504

**Comment by philips** [comment]
lgtm

**Comment by vbatts** [comment]
Rebase please

**Comment by yifan-gu** [comment]
Rebased.

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
