### PR TITLE
*: merge various extensions to master

### PR DESCRIPTION
**Pull request by jonboulle**

### CODE REVIEW

**Comment by s-urbaniak** [comment]
LGTM (I have no merge permissions though)

**Comment by lucab** [comment]
Also LGTM (but I have no powers here).

As a spec followup, the following elements should be properly documented:
 * UserAnnotations
 * UserLabels
 * AppVolume
 * os/linux/oom-score-adj
 * os/linux/cpu-shares
 * HostIP + PodPort

**Comment by squeed** [comment]
LGTM, but I wrote most of this :-).
If noone has any objections, I'll merge this tomorrow. I'll file a follow-up issue for the documentation.

**Comment by s-urbaniak** [comment]
@squeed :+1:

**Pull request merged**
