### PR TITLE
schema: standardise on supplementaryGIDs

### LINKED ISSUE #511: spec: supplementaryGroups or supplementaryGids?
#339 introduced supplementary GIDs in the spec.

In [the schema](https://github.com/appc/spec/blob/e040d35a7bb35a343f04c0f022a669968699d06a/spec/aci.md#image-manifest-schema) they are called "supplementaryGids" but the [app parser](https://github.com/appc/spec/blob/e040d35a7bb35a343f04c0f022a669968699d06a/schema/types/app.go#L29) expects them to be called "supplementaryGroups".

### PR DESCRIPTION
**Pull request by jonboulle**
785b1ee5f39221f66884b416a9127e5fd0a7e31d introduced the ability for
users to set supplementary group IDs, but unfortunately they were
inconsistently referenced: in the spec itself as `supplementaryGids` but
in the schema code and (actool) as `supplementaryGroups`.

Since it is unambiguously (as a list of ints) a list of group IDs, this
changes the schema and actool to match the spec.

Fixes #511

### CODE REVIEW

**Comment by jonboulle** [comment]
The spec is unchanged but this is a fixing-breaking change (the schema code was broken and now it's fixed).

**Comment by thockin** [comment]
nit: GIDs or Gids ?

**Comment by jonboulle** [comment]
gahhh, you're right - we already use imageID elsewhere, so..

**Comment by jonboulle** [comment]
OK, now it's a breaking schema change :-)

**Comment by jonboulle** [comment]
anyone? @thockin @philips @vbatts

**Comment by thockin** [comment]
Change LGTM, but I have been out of the loop for a while.

**Pull request merged**
