### PR TITLE
schema: Change 'val' abbreviation to 'value' for all name/value pairs.

### PR DESCRIPTION
**Pull request by cdaylward**
Update README, SPEC, types, and example manifests.

### CODE REVIEW

**Comment by jonboulle** [comment]
#92

**Comment by cdaylward** [comment]
(apologies for the dup, a habit of pushing refs instead of forcing a branch update)

**Comment by jonboulle** [comment]
:+1:

**Comment by alban** [comment]
This change of spec breaks the current images listed in rocket/README.md so they will need to be updated.

The etcd repository needs an update too:
```
$ sudo ./bin/rkt run coreos.com/etcd:v2.0.0-rc.1
rkt: starting to discover app img coreos.com/etcd:v2.0.0-rc.1
rkt: starting to fetch img from https://github.com/coreos/etcd/releases/download/v2.0.0-rc.1/etcd-v2.0.0-rc.1-linux-amd64.aci
Downloading aci: [================================             ] 4.44 MB/6.22 MB
run: error setting up stage0: error setting up image sha512-c9a0c14098226cec77facc170ae2a3d60c0b4ca38257c971da4e13e4f578ce67: error unmarshaling app manifest: bad os "" (must be one of: [darwin freebsd linux])
```

I made the change: https://github.com/coreos/etcd/pull/2061

**Pull request merged**
