### PR TITLE
vendor: Update kubernetes dependency

### PR DESCRIPTION
**Pull request by euank**
third_party/forked/reflect is gone from upstream, pick up that change

### CODE REVIEW

**Comment by squeed** [comment]
Cool, thanks!

**Comment by squeed** [comment]
@euank looks like you forgot to add some new files that were incorporated as part of this change - I'll fix it.

**Comment by squeed** [comment]
@euank My run of `glide-update` (with the changes in coreos/rkt#3313) generates a different result, see the [diff](https://github.com/euank/spec/compare/vendor-update-k8s...squeed:vendor-update-k8s). Any chance you just forgot to `git add -A vendor`?

**Comment by euank** [comment]
@squeed I didn't apply the changes from that rkt pr, and without them + glide v0.12.3 I reliably get what's PR'd here. I did not forget to `git add` stuff.

I don't think we need the `lock-file` bit for glide-vc in this repo since we're not vendoring tools, so it's fine to let it strip a little more.

**Comment by euank** [comment]
I cleaned up the glide script and removed the reference to `pkg/conversion` (that showed up in your diff from the lockfile but isn't referenced anywhere in this repo). Good catch on `pkg/conversion` being a bit odd there too!

**Comment by jonboulle** [comment]
LGTM

**Comment by jonboulle** [comment]
LGTM

**Pull request merged**
