### PR TITLE
schema/types: escape values when parsing

### LINKED ISSUE #465: schema/types: volume doesn't allow source paths with special URL characters
We parse volume parameters with [`url.ParseQuery`](https://github.com/appc/spec/blob/0d1edc37553152577a56f256279992200f142b48/schema/types/volume.go#L101). This means that if the `source` field includes special URL characters they would be interpreted (e.g. `+` is converted to a space) making impossible to use those directories.

### PR DESCRIPTION
**Pull request by iaguis**
To allow values with URL special characters like "+" or "&".

Fixes #465 

cc @krnowak

### CODE REVIEW

**Comment by krnowak** [comment]
LFAD.

**Comment by iaguis** [comment]
Ping?

**Comment by jonboulle** [comment]
Sorry, this fell through the cracks. 
@iaguis please add a test table, then lgtm...

**Comment by iaguis** [comment]
Added a test and fixed the examples in the function documentation to match the actual behavior :sweat_smile:

**Comment by jonboulle** [comment]
:+1: thank you sir

**Pull request merged**
