### PR TITLE
SPEC: add working directory

### PR DESCRIPTION
**Pull request by philips**
TODO: need to add validator logic

### CODE REVIEW

**Comment by philips** [comment]
@jonboulle sure, eventHandlers can have this too.

**Comment by philips** [comment]
@jonboulle @vcaputo This is in need of review, I added the validator logic.

**Comment by jonboulle** [comment]
@philips I guess we were talking about different kinds of validate logic.. Could you add an abspath check to assertValid to the schema?

**Comment by philips** [comment]
@jonboulle oops, duh, yes, will do.

**Comment by philips** [comment]
@jonboulle schema validation added. If it looks good to you then merge at will.

**Comment by jonboulle** [comment]
Jumped the gun on this a bit - it's not quite fully specified in this diff.
@philips see https://github.com/appc/spec/pull/78

**Pull request merged**
