### PR TITLE
spec: clarify value of implementing individual sections

### PR DESCRIPTION
**Pull request by jonboulle**
The appc spec consists of several key sections:
- App Container Image
- App Container Image Discovery
- App Container Pod
- App Container Executor
  - Metadata Service (arguably, this should be a separate item)

For newcomers to appc, there has sometimes been a (mis)perception that it is necessary to completely implement all of these together in order to successfully "use" the spec, or be considered a valuable implementation.

While it is fair to say that we (as designers of the spec) feel that the entire specification is useful - and, indeed, that implementing it all to work together provides immense value - we have also taken great pains to ensure that the sections are composable and each useful in themselves. Unfortunately this message isn't always clear, and the notion of having to implement the _entire_ specification in order to make use of _any_ of it can be offputting to some.

We should rework the language to be completely explicit that:
a) the different key sections of the spec are independently valuable
b) implementing different sections separately is even one of the key _values_ of the spec: composability and separation of concerns
c) compliance can/should be considered on a per-section basis

### CODE REVIEW

**Comment by jonboulle** [comment]
Heavy WIP but feedback encouraged to help shape this up.

**Comment by eyakubovich** [comment]
I would not have separate schema.md and instead include a schema at the end of relevant file.

**Comment by jonboulle** [comment]
@eyakubovich what's your rationale?

**Comment by jonboulle** [comment]
@eyakubovich what's your rationale?

**Comment by vbatts** [comment]
Can markdown source another file? Like an `#include ...`

I'm +1 on this but wonder if we might be able to have a canonical view as well.

**Comment by vbatts** [comment]
Also @jonboulle what else do you envision for this? Is it still a WIP?

**Comment by jonboulle** [comment]
@vbatts Very much. Needs a big rebase :-(

I would *love* that include behaviour, if you can find it it'l make me very happy ;-)

**Comment by vbatts** [comment]
> @vbatts Very much. Needs a big rebase :-(

Hmm

> I would love that include behaviour, if you can find it it'l make me very
happy ;-)

It seems like there should be one... Perhaps a pattern like 01_...md,
02_...md, etc, and a Makefile to cat them would be the must generic. There
seem to be a few preprocessors, but that requires a set up. :-(

**Comment by mpasternacki** [comment]
How about using an actual document generation toolchain? This might require changing source format, but would scale better than current "just a bunch of markdown files" approach. It would be easy to format the spec as a website, or as a printable PDF.

Two widely used toolchains come to mind: ReST-based [Sphinx](http://sphinx-doc.org/) (and associated hosting service [Read The Docs](https://readthedocs.org/), and XML-based [DocBook](http://docbook.org/).

Docker uses Markdown-based [MkDocs](http://www.mkdocs.org/). Never heard of that one before, and it's first Markdown-based documentation toolchain that I know. May be worth looking at too.

**Comment by vbatts** [comment]
spec/discovery.md seems to be missing

**Comment by jonboulle** [comment]
@vbatts updated

**Comment by vbatts** [comment]
I wish there were a git cp command so these split out files could keep
blame history. :-/

**Comment by jonboulle** [comment]
@vbatts ```
git blame -C spec/discovery.md | head
9db8f9292a89c SPEC.md (Alex Polvi       2014-11-26 14:36:42 -0800   1) ## App Container Image Discovery
9db8f9292a89c SPEC.md (Alex Polvi       2014-11-26 14:36:42 -0800   2) 
ced50186f2f2b SPEC.md (Yifan Gu         2015-05-07 15:50:39 -0700   3) An App Container Image name has a URL-like structure, for example `example.com/reduce-worker`.
ced50186f2f2b SPEC.md (Yifan Gu         2015-05-07 15:50:39 -0700   4) However, there is no scheme on this name, so it cannot be directly resolved to an App Container Image URL.
ced50186f2f2b SPEC.md (Yifan Gu         2015-05-07 15:50:39 -0700   5) Furthermore, attributes other than the name may be required to unambiguously identify an image (version, OS and architecture).
ced50186f2f2b SPEC.md (Yifan Gu         2015-05-07 15:50:39 -0700   6) These attributes are expressed in the **labels** field of the [Image Manifest](#image-manifest-schema).
ced50186f2f2b SPEC.md (Yifan Gu         2015-05-07 15:50:39 -0700   7) App Container Image Discovery prescribes a discovery process to retrieve an image based on the name and these attributes.
ced50186f2f2b SPEC.md (Yifan Gu         2015-05-07 15:50:39 -0700   8) 
2af4890257e97 SPEC.md (Jonathan Boulle  2015-01-13 16:33:49 -0800   9) Image Discovery is inspired by Go's [remote import paths](https://golang.org/cmd/go/#hdr-Remote_import_paths).
9db8f9292a89c SPEC.md (Alex Polvi       2014-11-26 14:36:42 -0800  10) 
```

**Comment by vbatts** [comment]
TIL about `-C`. thanks

**Comment by jonboulle** [comment]
@krobertson mind reviewing?

**Comment by krobertson** [comment]
LGTM

**Comment by vbatts** [comment]
Overall LGTM. I think it's fine to have some files named `aci.md` and others like `discovery.md` etc.

**Comment by jonboulle** [comment]
Doing this.

**Comment by vbatts** [comment]
\o/

**Pull request merged**
