### PR TITLE
GUIDE.md: footnotes formatting

### PR DESCRIPTION
**Pull request by vbatts**

### CODE REVIEW

**Comment by jonboulle** [comment]
@vbatts why? now we have to worry about ordering!

**Comment by vbatts** [comment]
perhaps it'll work fine as words too. but the base revision didn't work. the links were broken.

**Comment by jonboulle** [comment]
@vbatts oh you're right, bad brackets - could you kindly change () to [] ? thanks!

**Comment by vbatts** [comment]
updated

**Comment by jonboulle** [comment]
LGTM, thanks

**Pull request merged**
