### PR TITLE
Godeps: rewrite the Kuberentes import path.

### PR DESCRIPTION
**Pull request by yifan-gu**

### CODE REVIEW

**Comment by yifan-gu** [comment]
Fix #471

**Comment by yifan-gu** [comment]
@jonboulle Would like to get this in soon as https://github.com/GoogleCloudPlatform/kubernetes/pull/8951/commits will bump the spec version.

**Comment by yifan-gu** [comment]
Maybe get a lgtm from you guys? @vbatts @krobertson

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
thank you!

**Pull request merged**
