### PR TITLE
deps:  gogo/protobuf: use v0.2

### PR DESCRIPTION
**Pull request by steveeJ**
Motivation is to vendor only tagged dependencies.

### CODE REVIEW

**Comment by alban** [comment]
@lucab @onlyjob: rkt already depends on an unspecified version of protobuf:
https://anonscm.debian.org/cgit/pkg-go/packages/rkt.git/tree/debian/control#n50

Does it mean it is unnecessary to switch to a tagged version for this specific package?

**Comment by alban** [comment]
For the context: this is downgrading the dependency on gogo/protobuf to avoid a dependency on an untagged version. But v0.2 is quite old. A new tag has been requested on https://github.com/gogo/protobuf/issues/182

**Comment by onlyjob** [comment]
> rkt (package) already depends on an unspecified version of protobuf:

`golang-goprotobuf-dev` provides `github.com/golang/protobuf`.
If _rkt_ gained _direct_ dependency on `github.com/gogo/protobuf` then `golang-github-gogo-protobuf-dev` package (currently v0.2) should be added to rkt's Build-Depends.

Properly versioning dependencies is very helpful.

If only some of _rkt_ dependency packages use `github.com/gogo/protobuf` then corresponding packages should be updated with versioned dependency on `golang-github-gogo-protobuf-dev (>= 0.2)` (or higher, as required).

**Comment by onlyjob** [comment]
> But v0.2 is quite old.

That's rapid development, isn't it?  ;)
gogo-protobuf 0.2 is just about 2 months (and 17 commits) "old"!  :)

**Comment by lucab** [comment]
> For the context: this is downgrading the dependency on gogo/protobuf to avoid a dependency on an untagged version.

This doesn't look like a downgrade to me. Current revision falls between 0.1 and 0.2. If it is not causing any new regressions, I think this should be ok to be merged. Debian already has `golang-github-gogo-protobuf-dev` 0.2 anyway.

**Comment by jonboulle** [comment]
lgtm

**Pull request merged**
