### PR TITLE
README: add disclaimer note about appc future

### PR DESCRIPTION
**Pull request by jonboulle**

### CODE REVIEW

**Comment by jonboulle** [comment]
@vbatts @philips ?

**Comment by vbatts** [comment]
woof.

But what of the html discovery and signing? Will this be accommodated by a transition plan?

**Comment by philips** [comment]
LGTM

**Comment by jonboulle** [comment]
@vbatts seems to me that the onus of transition plans falls on tooling authors, not the spec

**Comment by jonboulle** [comment]
@vbatts added dist/signing ..?

**Comment by vbatts** [comment]
I reckon that'll do.

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
