### PR TITLE
spec: fix position of the dependencies size field description

### PR DESCRIPTION
**Pull request by derekchiang**
The ordering was incorrect.

### CODE REVIEW

**Comment by sgotti** [comment]
@derekchiang Perhaps the commit title should report what it fixes (something like `spec: fix position of the dependencies size field description`). Apart from this detail it LGTM.

**Comment by jonboulle** [comment]
welp, LGTM. @derekchiang could you please update your commit message as Simone said? thanks

**Comment by derekchiang** [comment]
done

**Comment by jonboulle** [comment]
thanks.

**Pull request merged**
