### PR TITLE
[issue/690] allow . and - in environment variable names.

### PR DESCRIPTION
**Pull request by ae6rt**
Files touched:  schema/types/environment.go, schema/types/environment_test.go

Allow additional characters in the set considered valid in environment variable names.  Prompted by
https://github.com/appc/docker2aci/issues/244 and https://github.com/rkt/rkt/issues/3532.

### CODE REVIEW

**Comment by ae6rt** [comment]
@lucab PTAL, taking you up on your offer:  https://github.com/rkt/rkt/issues/3532#issuecomment-279013222

**Comment by ae6rt** [comment]
The IEEE spec from which the original conservative character set is taken, as a reference:

http://pubs.opengroup.org/onlinepubs/9699919799/

**Comment by lucab** [comment]
@ae6rt thanks for the PR, can you please also update `SPEC.md` for the new characters?

**Comment by ae6rt** [comment]
I updated spec/aci.md, and rebased.  I wanted to honor the desire to adhere to the IEEE spec, so I left the word 'solely' in, with a qualifying clause about the practical desire to allow . and -.   I hope it doesn't read strangely.

**Comment by ae6rt** [comment]
Ping @lucab knowing you are busy, but I don't want to forget about this.

**Comment by lucab** [comment]
LGTM, but I don't have merge powers here.

**Pull request merged**
