### PR TITLE
*: appc v0.8.5

### PR DESCRIPTION
**Pull request by jonboulle**

### CODE REVIEW

**Comment by jonboulle** [comment]
apparently some bugs in isolatorvalues, stand by

**Comment by lucab** [comment]
@jonboulle it turned out this may not be a real bug in validator, but rkt misusing it. See https://github.com/appc/spec/pull/633#issuecomment-228107843 for reference, but it only adds a graceful handler to an error case.

**Comment by jonboulle** [comment]
@lucab updated

**Comment by euank** [comment]
LGTM

**Pull request merged**
